### ISSUE TITLE
Custom parser files

### ISSUE THREAD

**Issue by ghost** [orachide/ansible-role-fluentbit#10]
Hey! 

I'm trying to setup some custom parser files and include them in the config to be used by the inputs.

The parser files aren't copied to the server, shouldn't they be?

How do you suggest doing it? 

Thanks!

**Comment by orachide** [comment]
Hello,

Sorry for the delay, you can have a look to https://github.com/orachide/ansible-role-fluentbit/blob/master/molecule/default/playbook.yml#L15

There is an example of how to add custom file.
Regards
